import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '/home',
    title: 'Inicio',
    label: '',
    icon: 'mdi mdi-home',
    class: '',
    labelClass: '',
    extralink: false,
    submenu: [],
    permisos: [],
  },
  // ******************************************************
  {
    path: '/',
    title: 'CRM',
    label: '',
    icon: 'mdi mdi-account-multiple',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    submenu: [],
    permisos: ["crm"],
  },
  {
    path: '/',
    title: 'Ventas',
    label: '',
    icon: 'mdi mdi-chart-areaspline',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["ventas"],
    submenu: [
      {
        path: '/ventas/notacredito',
        label: '',
        labelClass: '',
        title: 'Nota Crédito',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["ventas_notacredito"],
      },
      {
        path: '/ventas/cotizacion',
        label: '',
        labelClass: '',
        title: 'Cotizaciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["ventas_cotizacion"],
      },
      {
        path: '/ventas/factura',
        label: '',
        labelClass: '',
        title: 'Factura',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["ventas_cotizacion"],
      },
      {
        path: '/ventas/cotizacion-seguimiento',
        label: '',
        labelClass: '',
        title: 'Cotiz. Seguimiento',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["ventas_cotizacion_seguimiento"],
      },
      {
        path: '/ventas/pedidos-empleado',
        label: '',
        labelClass: '',
        title: 'Pedidos Empleado',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["ventas_pedido_empleado"],
      },
      {
        path: '/ventas/ofertas-consulta-factura',
        label: '',
        labelClass: '',
        title: 'Consulta de ofertas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["ventas_ofertas_consulta_factura"],
      },
      {
        path: '',
        title: 'Reportes de Ventas',
        icon: 'mdi mdi-chart-areaspline',
        labelClass: '',
        label: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["ventas_reportes"],
        submenu: [
          {
            path: '/ventas/reportes-de-ventas/reporte-ofertas-otorgadas',
            label: '',
            labelClass: '',
            title: 'Ofertas Otorgadas',
            icon: '',
            class: '',
            extralink: false,
            submenu: [],
            permisos: ["ventas_reportes_ofertas_otorgadas"],
          },
          {
            path: '/ventas/reporteprontopago',
            label: '',
            labelClass: '',
            title: 'Pronto Pago',
            icon: '',
            class: '',
            extralink: false,
            submenu: [],
            permisos: ["ventas_reporte_prontopago"]
          },
        ]
      },
    ],
  },
  {
    path: '/',
    title: 'Compras',
    label: '',
    icon: 'mdi mdi-basket',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["compras"],
    submenu: [
      {
        path: '/compras/solicitud-compras',
        label: '',
        labelClass: '',
        title: 'Solicitud de compras',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["compras_solicitud_compra"],
      },
      {
        path: '/compras/orden-compras',
        label: '',
        labelClass: '',
        title: 'Orden de compras',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["compras_orden_compra"],
      },
    ],
  },
  {
    path: '/',
    title: 'Finanzas',
    label: '',
    icon: 'mdi mdi-cash-usd',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["finanzas"],
    submenu: [
      {
        path: '/',
        label: '',
        labelClass: '',
        title: 'Cuentas Por Cobrar',
        icon: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["finanzas_cuentas_por_cobrar"],
        submenu: [
          {
            path: '/finanzas/cuentas-por-cobrar/cheques-devueltos',
            label: '',
            labelClass: '',
            title: 'Cheques Devueltos',
            icon: '',
            class: '',
            extralink: false,
            permisos: ["finanzas_cuentas_por_cobrar_cheques_devueltos"],
            submenu: [],
          },
        ],
      },
    ],
  },
  {
    path: '/',
    title: 'Recursos Humanos',
    label: '',
    icon: 'mdi mdi-account-box',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    submenu: [],
    permisos: ["recursos-humanos"],
  },
  {
    path: '',
    title: 'Inventario',
    label: '',
    icon: 'mdi mdi-package-variant-closed',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["inventario"],
    submenu: [
      {
        path: '/inventario/devoluciones',
        title: 'Devoluciones',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['inventario_devoluciones'],
      },
      {
        path: '/inventario/recepcionactivo',
        title: 'Recepción Activo',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['inventario_recepcionactivo'],
      },
      {
        path: '/inventario/entregas',
        title: 'Entregas',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['inventario_entregas'],
      },
      {
        path: '/inventario/despacho',
        title: 'Despacho',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['despacho'],
      },
      {
        path: '/inventario/despacho-asignacion',
        title: 'Despacho Asignacion',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['asignacion_despacho'],
      },
      {
        path: '/inventario/transferencia',
        title: 'Transferencia',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['inventario_transferencia_despacho'],
      },
      {
        path: '/inventario/solicitud-devolucion',
        title: 'Solicitud de Devolución',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['inventario_solicitud_devolucion'],
      },
      {
        path: '/inventario/solicitud-cambio',
        title: 'Solicitud Cambio',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['inventario_solicitud_cambio'],
      },
      {
        path: '/inventario/almacen-inventario',
        title: 'Almacén Inventario',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['inventario_transferencia_despacho'],
      },
    ],
  },

  {
    path: '/',
    title: 'Produccion',
    label: '',
    icon: 'mdi mdi-archive',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["produccion"],
    submenu: [
      {
        path: '/produccion/pesajeListado',
        label: '',
        labelClass: '',
        title: 'Pesaje Listado',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["produccion_pesaje_listado"],
      },
      {
        path: '/produccion/pesajeApp',
        label: '',
        labelClass: '',
        title: 'Sistema de Pesajes',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["produccion_pesaje_app"],
      },
      {
        path: '/produccion/ordenfabricacion',
        label: '',
        labelClass: '',
        title: 'Orden Fabricación',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["produccion_ordenfabricacion"],
      },
    ],
  },


  {
    path: '/',
    title: 'Servicios',
    label: '',
    icon: 'mdi mdi-view-module',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["servicios"],
    submenu: [],
  },


  // ******************************************************




  {
    path: '#',
    title: 'Turno',
    label: '',
    icon: 'mdi mdi-home',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["turnos"],
    submenu: [
      {
        path: '/turno/servicios',
        label: '',
        labelClass: '',
        title: 'Servicios',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["turnos_pantalla"],
      },
      {
        path: '/turno/listado',
        label: '',
        labelClass: '',
        title: 'Listado',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["turnos_listado"],
      },
      {
        path: '/turno/entregas',
        label: '',
        labelClass: '',
        title: 'Entregas',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["turnos_entregas"]
      },
    ]
  },

  {
    path: '',
    title: 'Servicios Viacloud',
    icon: 'mdi mdi-bullseye',
    labelClass: '',
    label: '',
    class: 'has-arrow',
    extralink: false,
    permisos: ["servicios-viacloud"],
    submenu: [
      {
        path: '/servicios/citas',
        label: '',
        labelClass: '',
        title: 'Citas',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_citas"],
      },
      {
        path: '/servicios/recepcion-llamado',
        label: '',
        labelClass: '',
        title: 'Recepción',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_recepcion_llamado"],
      },
      {
        path: '/servicios/ordenes',
        label: '',
        labelClass: '',
        title: 'Mis ordenes de servicio',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_ordenes_de_servicio"],
      },
      {
        path: '/servicios/ordeness',
        label: '',
        labelClass: '',
        title: 'Ordenes de servicio',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_ordenes_de_servicio_general"],
      },
      {
        path: '/servicios/multipuntos',
        label: '',
        labelClass: '',
        title: 'Multipuntos Taller',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_multipuntos"],
      },

    ]
  },
  {
    path: '',
    title: 'Herramientas',
    icon: 'mdi  mdi-wrench',
    labelClass: '',
    label: '',
    class: 'has-arrow',
    extralink: false,
    permisos: ["herramientas"],
    submenu: [
      {
        path: '/herramientas/minutas',
        label: '',
        labelClass: '',
        title: 'Minutas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["herramientas_minutas"],
      },
      {
        path: '/herramientas/oasisFord',
        label: '',
        labelClass: '',
        title: 'Oasis Ford',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["herramientas_oasis_ford"],
      },


    ]
  },


  {
    path: '',
    title: 'Mantenimientos',
    icon: 'mdi mdi-table',
    labelClass: '',
    label: '',
    class: 'has-arrow',
    extralink: false,
    permisos: ["mantenimientos"],

    submenu: [
      {
        path: '/mantenimientos/articulo',
        label: '',
        labelClass: '',
        title: 'Artículos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_articulo"],
      },
      /*{
        path: '/mantenimientos/asignacion-almacen',
        label: '',
        labelClass: '',
        title: 'Asignación Almacén',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_hora_picking"],
      },*/
      {
        path: '/mantenimientos/articulo-categoria',
        label: '',
        labelClass: '',
        title: 'Artículos Categorias',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_articulo_categoria"],
      },
      {
        path: '/mantenimientos/actividadEconomica',
        label: '',
        labelClass: '',
        title: 'Actividad Económica',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_actividad_economica"],
      },
      {
        path: '/mantenimientos/almacen',
        label: '',
        labelClass: '',
        title: 'Almacenes',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_almacen"],
      },
      
      // {
      //   path: '/mantenimientos/autorizacionprecios',
      //   label: '',
      //   labelClass: '',
      //   title: 'Autorización de precios',
      //   icon: '',
      //   class: '',
      //   extralink: false,
      //   submenu: [],
      //   permisos: ["mantenimientos_autorizacion_precios"],
      // },
      {
        path: '/mantenimientos/moneda',
        label: '',
        labelClass: '',
        title: 'Moneda',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_moneda"],
      },
      {
        path: '/mantenimientos/hora-picking',
        label: '',
        labelClass: '',
        title: 'Hora Picking',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_hora_picking"],
      },
     
      {
        path: '/mantenimientos/listaprecios',
        label: '',
        labelClass: '',
        title: 'Lista de precios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_listas_precios"],
      },

      {
        path: '/mantenimientos/comprobante-fiscal',
        label: '',
        labelClass: '',
        title: 'Comprobante Fiscal',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_comprobante_fiscal"],
      },

      {
        path: '/mantenimientos/comprobante-fiscal-enrroll',
        label: '',
        labelClass: '',
        title: 'Comprobante Fiscal Enroll',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_comprobante_fiscal_enroll"],
      },
      {
        path: '/mantenimientos/tipo-comprobante-fiscal',
        label: '',
        labelClass: '',
        title: 'Tipo Comprobante Fiscal',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_tipos_comprobante_fiscal"],
      },

      {
        path: '/mantenimientos/cargamasiva',
        label: '',
        labelClass: '',
        title: 'Carga Masiva',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_carga_masiva"],
      },
      {
        path: '/mantenimientos/plazo',
        label: '',
        labelClass: '',
        title: 'Plazos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_plazo"],
      },
      {
        path: '/mantenimientos/promocion',
        label: '',
        labelClass: '',
        title: 'Promociones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_promocion"],
      },
      {
        path: '/mantenimientos/descuentos',
        label: '',
        labelClass: '',
        title: 'Descuento',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_descuento"],
      },
      {
        path: '/mantenimientos/departamento',
        label: '',
        labelClass: '',
        title: 'Departamentos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_departamento"],
      },
      {
        path: '/mantenimientos/ruta',
        label: '',
        labelClass: '',
        title: 'Rutas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_ruta"],
      },

      {
        path: '/mantenimientos/roles',
        label: '',
        labelClass: '',
        title: 'Roles',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_rol"],
      },

      {
        path: '/mantenimientos/permisos',
        label: '',
        labelClass: '',
        title: 'Permisos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_permiso"],
      },
      {
        path: '/mantenimientos/modulo',
        label: '',
        labelClass: '',
        title: 'Modulo',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_permiso"],
      },
      
      {
        path: '/mantenimientos/proveedor',
        label: '',
        labelClass: '',
        title: 'Proveedores',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_proveedor"],
      },
      {
        path: '/mantenimientos/enrrollvendedorentregasupervisor',
        label: '',
        labelClass: '',
        title: 'Comisiones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: [""],
      },

















      {
        path: '/mantenimientos/accesorio',
        label: '',
        labelClass: '',
        title: 'Accesorios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_accesorios"],
      },


      {
        path: '/mantenimientos/cita-categoria',
        label: '',
        labelClass: '',
        title: 'Cita Categorias',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_cita_categoria"],
      },
      {
        path: '/mantenimientos/comite',
        label: '',
        labelClass: '',
        title: 'Comites',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_comite"],
      },
      {
        path: '/mantenimientos/combustible',
        label: '',
        labelClass: '',
        title: 'Combustibles',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_combustible"],
      },
      {
        path: '/mantenimientos/compania',
        label: '',
        labelClass: '',
        title: 'Compañías',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_compania"],
      },
      {
        path: '/mantenimientos/cliente',
        label: '',
        labelClass: '',
        title: 'Clientes',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_cliente"],
      },
      {
        path: '/mantenimientos/dealer',
        label: '',
        labelClass: '',
        title: 'Dealers',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_dealer"],
      },

      {
        path: '/mantenimientos/marca',
        label: '',
        labelClass: '',
        title: 'Marcas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_marca"],
      },
      {
        path: '/mantenimientos/modelo',
        label: '',
        labelClass: '',
        title: 'Modelos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_modelo"],
      },
      {
        path: '/mantenimientos/recall',
        label: '',
        labelClass: '',
        title: 'Recall',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_recall"],
      },
      {
        path: '/mantenimientos/oferta',
        label: '',
        labelClass: '',
        title: 'Oferta',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_oferta"],
      },
      {
        path: '/mantenimientos/receptor-posicion',
        label: '',
        labelClass: '',
        title: 'Receptores Posiciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_receptor_posicion"],
      },
      {
        path: '/mantenimientos/sintoma',
        label: '',
        labelClass: '',
        title: 'Síntomas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_cita_sintomas"],
      },
      {
        path: '/mantenimientos/sintoma-categoria',
        label: '',
        labelClass: '',
        title: 'Síntoma Categorias',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_cita_sintoma_categoria"],
      },
      {
        path: '/mantenimientos/sucursal',
        label: '',
        labelClass: '',
        title: 'Sucursales',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_sucursal"],
      },
      {
        path: '/mantenimientos/tag',
        label: '',
        labelClass: '',
        title: 'Tags',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_tag"],
      },

      {
        path: '/mantenimientos/usuario-almacen-enrroll',
        label: '',
        labelClass: '',
        title: 'Usuarios Almacen Enrroll',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_usuario_almacen_enrroll"],
      },
      {
        path: '/mantenimientos/vehiculocondicion',
        label: '',
        labelClass: '',
        title: 'Vehículo Condiciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_vehiculo_condicion"],
      },
      {
        path: '/mantenimientos/vehiculotipo',
        label: '',
        labelClass: '',
        title: 'Vehículo Tipos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_vehiculo_tipo"],
      },
      {
        path: '/mantenimientos/tomainventarioruta',
        label: '',
        labelClass: '',
        title: 'Asignacion de rutas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_asignaciones_rutas"],
      },
      {
        path: '/mantenimientos/tipoSolicitudDevolucion',
        label: '',
        labelClass: '',
        title: 'Tipo Solicitud Devolución',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_tipo_solicitud_devolucion"],
      },
      {
        path: '/mantenimientos/tipo-descuento',
        label: '',
        labelClass: '',
        title: 'Tipo Descuento',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_tipo_descuento"],
      },
      {
        path: '/mantenimientos/descuento-articulos',
        label: '',
        labelClass: '',
        title: 'Descuento Articulos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_descuento_articulos"],
      },
      {
        path: '/mantenimientos/promociones',
        label: '',
        labelClass: '',
        title: 'Promociones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_promociones"],
      },
    ]
  },
  {
    path: '/',
    title: 'Autorización',
    label: '',
    icon: 'mdi mdi-checkbox-marked-circle',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["autorizacion"],
    submenu: [
      {
        path: '/autorizacion/autorizacion-historico',
        label: '',
        labelClass: '',
        title: 'Histórico',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["autorizacion_historico"],
      },
      {
        path: '/autorizacion/autorizacionprecios',
        label: '',
        labelClass: '',
        title: 'Lista de precios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["autorizacion_lista_precios"],
      },
      {
        path: '/compras/solicitud-compras-autorizacion',
        label: '',
        labelClass: '',
        title: 'Solicitud de compras',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["autorizacion_solicitud_compras"],
      },
      {
        path: '/autorizacion/autorizaciondevoluciones',
        title: 'Devoluciones',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['autorizacion_devoluciones'],
      },
      {
        path: '/ventas/autorizacioncotizacion',
        title: 'Cotizaciones',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['autorizacion_cotizaciones'],
      },
      {
        path: '/autorizacion/autorizacion-pedidos',
        title: 'Pedidos',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['autorizacion_cotizaciones'],
      },
      {
        path: '/autorizacion/autorizacion-ordenfabricacion',
        title: 'Orden Fabricacion',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['autorizacion_ordenfabricacion'],
      },
    ],
  },


  {
    path: '/',
    title: 'Reportes',
    label: '',
    icon: 'mdi mdi-file-chart',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["reportes"],
    submenu: [
      {
        path: '/',
        label: '',
        labelClass: '',
        title: 'Inventario',
        icon: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["reportes_inventario"],
        submenu: [
          {
            path: '/reportes/inventario/existencia',
            label: '',
            labelClass: '',
            title: 'Existencia',
            icon: '',
            class: '',
            extralink: false,
            permisos: ["reportes_inventario_existencia"],
            submenu: [
            ],
          },
          {
            path: '/reportes/inventario/entrega-pedidos',
            label: '',
            labelClass: '',
            title: 'Entrega Pedidos',
            icon: '',
            class: '',
            extralink: false,
            permisos: ["reportes_inventario_entrega_pedidos"],
            submenu: [
            ],
          },

          {
            path: '/reportes/inventario/inventario-activo',
            label: '',
            labelClass: '',
            title: 'Inventario activo',
            icon: '',
            class: '',
            extralink: false,
            permisos: ["reportes_inventario_existencia"],
            submenu: [
            ],
          },

          {
            path: '/reportes/inventario/reporte-canasto',
            label: '',
            labelClass: '',
            title: 'Reporte Canasto',
            icon: '',
            class: '',
            extralink: false,
            permisos: ["reportes_inventario_reportecanasto"],
            submenu: [
            ],
          },
        ],
      },

    ],
  },

  {
    path: '',
    title: 'Configuraciones',
    icon: 'mdi  mdi-settings',
    labelClass: '',
    label: '',
    class: 'has-arrow',
    extralink: false,
    permisos: ["configuraciones"],
    submenu: [
      {
        path: '/mantenimientos/usuario',
        label: '',
        labelClass: '',
        title: 'Usuarios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_usuario"],
      },
      {

        path: '/mantenimientos/nivelautorizacion',
        label: '',
        labelClass: '',
        title: 'Nivel Autorizacion',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_nivel_autorizacion"],
      },
      {

        path: '/mantenimientos/nivelautorizacionmodulo',
        label: '',
        labelClass: '',
        title: 'Nivel Autorizacion M.',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_nivel_autorizacion_modulo"],
      },
      {
        path: '/mantenimientos/estadosgenerales',
        label: '',
        labelClass: '',
        title: 'Estados Generales',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_estado_general"],
      },
      {
        path: '/mantenimientos/configuracion-compania',
        label: '',
        labelClass: '',
        title: 'Configuración Compañia',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_configuration_compania"],
      },
      {
        path: '/mantenimientos/sapconnection',
        label: '',
        labelClass: '',
        title: 'Conexiones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_sap_conexion"],
      },
      {
        path: '/configuraciones/admin-web-panel-sincronizacion',
        label: '',
        labelClass: '',
        title: 'Admin Sincronización',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["configuraciones_admin_panel_sincronizacion"],
      },

      {
        path: '/configuraciones/sap-panel-sincronizacion',
        label: '',
        labelClass: '',
        title: 'SAP Sincronización',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["configuraciones_sap_panel_sincronizacion"],
      },
      {
        path: '/configuraciones/modulo-compania-enrroll',
        label: '',
        labelClass: '',
        title: 'Modulo Compañia Enrroll',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["configuraciones_modulo-compania-enrroll"],
      },
      {
        path: '/mantenimientos/permisos',
        label: '',
        labelClass: '',
        title: 'Permisos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_permiso"],
      },


















      {
        path: '/configuraciones/horario-citas',
        label: '',
        labelClass: '',
        title: 'Horario Citas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["configuraciones_horario_cita"],
      },


    ]
  },




];
