export enum OrdenFabricacionEstadoEnum {
  PLANIFICADA = 1,
  PENDIENTECONSUMO = 2,
  PROCESANDOCONSUMO = 3,
  PENDIENTEAUTORIZARCONSUMO = 4,
  PENDIENTETERMINALREPORT = 5,
  PENDIENTECERRAR = 6,
  PENDIENTECERRARSUPERVISORPRODUCCION = 7,
  PENDIENTECERRARGERENTEPRODUCCION = 8,
  PENDIENTECERRARGERENTEPLANTA = 9,
  PENDIENTECERRARADMINISTRACION = 10,
  CERRADA = 11
}

export enum OrdenFabricacionTipoEnum {
  ESTANDAR = 1,
  ESPECIAL = 2,
  DESMONTAR = 3,
}

export enum OrdenFabricacionDetalleEstadoEnum {
  NOCONSUMIDO = 0,
  CONSUMIDO = 1,
  PENDIENTEAUTORIZAR = 2
}
